"""agregar campo estado a reservas

Revision ID: 65033d2abbc6
Revises: 8e03c297d3b8
Create Date: 2025-07-01 19:19:07.801960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65033d2abbc6'
down_revision = '8e03c297d3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=False, server_default='esperando_retiro'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
