"""agrego tabla mantenimientos_maquinaria

Revision ID: 8e03c297d3b8
Revises: f125eb59e7db
Create Date: 2025-06-16 18:40:40.089530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e03c297d3b8'
down_revision = 'f125eb59e7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mantenimientos_maquinaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('maquinaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['maquinaria_id'], ['maquinaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mantenimientos_maquinaria')
    # ### end Alembic commands ###
