"""agregar campo mantenimiento a maquinaria

Revision ID: abc123456789
Revises: 65033d2abbc6
Create Date: 2025-07-09 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc123456789'
down_revision = '65033d2abbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquinaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mantenimiento', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquinaria', schema=None) as batch_op:
        batch_op.drop_column('mantenimiento')

    # ### end Alembic commands ###
