"""Agrego campos a Maquinaria y Categoria

Revision ID: f125eb59e7db
Revises: 
Create Date: 2025-06-04 15:46:44.101469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f125eb59e7db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquinaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('politicas_reembolso', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_maquinaria_categoria', 'categoria', ['categoria_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('dni_numero',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('dni_numero',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('maquinaria', schema=None) as batch_op:
        batch_op.drop_constraint('fk_maquinaria_categoria', type_='foreignkey')
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('politicas_reembolso')

    # ### end Alembic commands ###
